### ISSUE TITLE
Change emptyStateTitle in runtime? #question

### ISSUE THREAD

**Issue by martin-one** [luispadron/UIEmptyState#27] opened 2019-01-02 01:36 UTC
Is there a way to set a different message title when it load, but then, when user do something (i.e push button) change the title?

**Comment by luispadron** [comment] 2019-01-02 01:44
Yes, you can change the title using the methods described in the docs.
This is just a matter of hooking up an action and performing on user tap.

I'm closing this issue as it is not a bug. Please feel free to ask this question for more help on StackOverflow

**Closed as completed by luispadron** 2019-01-02 01:44 UTC
Labels: question
